### ISSUE TITLE
Extend data model to track cleanliness

### ISSUE THREAD

**Issue by jonathanba** [TU-CP18/cp18-backend#107]
**Description:**

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by andresest83** [comment]
![image.png](https://images.zenhubusercontent.com/5be1d48851a86d10bae531b9/852b63b1-62d2-4a8d-bafd-52275332d89e)

**Comment by nschoen** [comment]
Thanks. As discussed, add an endpoint `POST /api/cars/{carId}/cleanliness` to be able to specify the car id, please.

**Comment by andresest83** [comment]
After clarification, the post is done to /api/car-cleanliness and the json is formatted accordingly, cleanliness is also shown now in the detail page of a car.
