### ISSUE TITLE
#63 #64 Fix Fleet Schedule Bugs

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#115]
**Bugs to fix:**

- [ ] Initial data loading breaks sporadically
- [ ] Detailed shift created popup does not render if selected time slot is behind an existing shift
- [ ] Shift detail popup shows incorrect labels
- [ ] eventManager duplicates shifts

**Comment by jonathanba** [comment]
@tomcory Can we close this issue?
