### ISSUE TITLE
Authorize safety driver to open car

### ISSUE THREAD

**Issue by calvinschmidt** [TU-CP18/cp18-backend#117]
**Is your feature request related to a problem? Please describe.**
When the safety driver arrives at the vehicle, he should press a button to open the car. When this button is pressed, the mobile app sends a request to the backend that should authorize this safety driver.

**Describe the solution you'd like**
The new endpoint should have:

- method: POST
- path: /shifts/{shiftID}/authorize
- payload: the safety driver's current location, JSON object like { latitude: x, longitude: y }
- return: 200 on success, 403 otherwise

The backend should do the following checks:

- [x] check if safety driver is currently assigned to a shift
- [x] check if safety driver is in intercept vehicle state
- [x] optional: check if sent GPS location nearly matches the current location of the car (ca. 20 meters)

**Comment by jonathanba** [comment]
Hi, @calvinschmidt I think it's finished. Please try it out and move it to done once you are satisfied.
