### ISSUE TITLE
Add driver

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#37]
**Description:**

As a driver, I'm not able to register on my own. As a fleet manager, I want to create new drivers.

**Acceptance criteria:**

- [x] registration is not possible anymore (from the webapp)
- [x] new view for creating users (for fleet manager)
- [x] new API endpoint to create user -> connect User and SafetyDriver
- [x] auto password
- [x] password is sent to the safety driver automatically

**Comment by jonathanba** [comment]
@tomcory @captainsano please check out my branch and the creation of the safety drivers. TODO for myself auto password generation and email to new safety driver.
