### ISSUE TITLE
Chat (FM+SD)

### ISSUE THREAD

**Issue by nschoen** [TU-CP18/cp18-backend#45]
**Description:**
As a Fleet manager I want to be able to contact all security drivers to chat with them.
Also I want to see my Chat History and be notified on new incoming messages.
Please find out which technology is most suitable (we can probably use something like this: https://code.tutsplus.com/tutorials/build-a-real-time-chat-application-with-modulus-and-spring-boot--cms-22513)

Related Frontend Ticket: https://github.com/TU-CP18/cp18-app/issues/26

**Acceptance criteria:**

- [x] Research and decide on the technology we want to use
- [x] Implement endpoints/websockets for the app
- [x] Make sure that the Chat history is stored somewhere
- [ ] Make sure history is loaded when the user opens the chat window.

**Comment by clemenspeters** [comment]
TODO: Make sure that the Chat history is stored somewhere.
