### ISSUE TITLE
As a Fleet Manager, I want to remove Safety Drivers from the system.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#56]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by jonathanba** [comment]
0ceb28ffefbc81b04c61c6b72af648114293fc8c

**Comment by jonathanba** [comment]
1fd9c43eef78bb7b08f0bdb406eb2a79e2d662b9
