### ISSUE TITLE
As a Fleet Manager, I want to get an overview of the status of all Safety Drivers.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#57]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] Given I’m in a role of a signed-in fleet manager, when I open the Safety Drivers’ management page, then the system shows a list of all the drivers.
- [x] Given that I have a list of all the drivers, when I browse to the top of the list, the the system shows a graph containing all the Safety Drivers grouped by Status.

**Comment by jonathanba** [comment]
48b22f88f49affc66d849425808b002ce819fd5f
