### ISSUE TITLE
As a Fleet Manager, I want to view the status of any vehicle within the fleet.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#61]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [x] The fleet manager can view a list of all vehicles.
- [ ] The fleet manager is presented with a graph containing all the vehicles grouped by status.

**Comment by jonathanba** [comment]
@andresest83 Same like with the SafetyDriver... just add the same graphical view
