### ISSUE TITLE
Fleet manager dashboard

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#62]
**Details:**

Create a specialized fleet manager dashboard where a map shows the near-realtime position and status of vehicles and drivers. A summary of various metrics should be displayed and further investigation should be made possible through child views.

**Acceptance criteria:**

- [x] Dashboard map
- [x] Periodically update vehicle positions
- [ ] Click on vehicle to view its logs
- [x] Host as an iframe in the fleet manager app

**Comment by jonathanba** [comment]
@captainsano Let's discuss it the next meeting. I have a great idea
