### ISSUE TITLE
As a Fleet Manager, I want to assign Safety Drivers to newly created shifts.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#66]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by jonathanba** [comment]
3eaa8142a4088c67e210290cd54c60053118b59d

**Comment by jonathanba** [comment]
48b22f88f49affc66d849425808b002ce819fd5f
