### ISSUE TITLE
As a Fleet Manager, I want to communicate via text with Safety Drivers to support them in their activities.

### ISSUE THREAD

**Issue by tomcory** [TU-CP18/cp18-backend#72]
**Details:**

**Tasks:**

- [ ]
- [ ]

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by clemenspeters** [comment]
see
https://github.com/TU-CP18/cp18-app/issues/26
https://github.com/TU-CP18/cp18-backend/issues/45
