### ISSUE TITLE
add NoSQL connection to backend for logging

### ISSUE THREAD

**Issue by jonathanba** [TU-CP18/cp18-backend#81]
**Description:**

Probably MongoDB...

**Acceptance criteria:**

- [ ]
- [ ]

**Comment by jonathanba** [comment]
Ok, since the Logs are your work I would suggest you can choose what you want to.

**Comment by jonathanba** [comment]
@captainsano would be great to finish this issue until new year

**Comment by captainsano** [comment]
@jonathanba we are using the ELK stack for tracking all logs now and have a dedicated node microservice for this.
